theme: jekyll-theme-minimal
title: Gamal Abdelgadir
description: Hi I'm Gamal and I am a junior student majoring in Information Technology. In my freetime I like to workout and play sports. I also like programming and learning how to make software. 
